/**
 * @fileoverview 业务场景模板数据
 * @description 预定义的30+业务场景模板，涵盖各种常见应用场景
 */

import type { Scenario } from '@/types/recommendation';

export const SCENARIO_TEMPLATES: Scenario[] = [
  {
    id: 'auth-login-form',
    name: '用户登录表单',
    description: '标准用户登录界面，包含用户名/邮箱和密码输入，支持记住登录状态',
    category: 'authentication',
    keywords: ['login', 'signin', 'auth', 'login-form', 'password', 'signin-form'],
    complexity: 'low',
    popularity: 95,
    tags: ['authentication', 'forms', 'security'],
    components: [
      { name: 'Input', required: true, position: { x: 0, y: 0 } },
      { name: 'PasswordInput', required: true, position: { x: 0, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['primary'] },
      { name: 'Checkbox', required: false, position: { x: 0, y: 3 } },
      { name: 'Link', required: false, position: { x: 0, y: 4 } },
    ],
    dependencies: [
      { from: 'Input', to: 'FormField', type: 'required', weight: 1 },
      { from: 'PasswordInput', to: 'FormField', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'auth-register-form',
    name: '用户注册表单',
    description: '完整的用户注册流程，包含邮箱验证、密码强度检查、用户协议同意',
    category: 'authentication',
    keywords: ['register', 'signup', 'auth', 'register-form', 'signup-form', 'sign-up'],
    complexity: 'medium',
    popularity: 88,
    tags: ['authentication', 'forms', 'validation'],
    components: [
      { name: 'Input', required: true, position: { x: 0, y: 0 }, variants: ['email'] },
      { name: 'PasswordInput', required: true, position: { x: 0, y: 1 } },
      { name: 'ConfirmPasswordInput', required: true, position: { x: 0, y: 2 } },
      { name: 'Checkbox', required: true, position: { x: 0, y: 3 } },
      { name: 'Button', required: true, position: { x: 0, y: 4 }, variants: ['primary'] },
      { name: 'Link', required: true, position: { x: 0, y: 5 } },
    ],
    dependencies: [
      { from: 'PasswordInput', to: 'PasswordStrength', type: 'required', weight: 1 },
      { from: 'ConfirmPasswordInput', to: 'PasswordInput', type: 'peer', weight: 1 },
    ],
  },
  {
    id: 'auth-mfa-setup',
    name: '多因素认证设置',
    description: '双因子认证配置界面，支持SMS、邮件和Authenticator App',
    category: 'authentication',
    keywords: ['mfa', '2fa', 'two-factor', 'authenticator', 'verification'],
    complexity: 'high',
    popularity: 65,
    tags: ['security', 'authentication', 'advanced'],
    components: [
      { name: 'QRCode', required: true, position: { x: 0, y: 0 } },
      { name: 'Input', required: true, position: { x: 0, y: 1 }, variants: ['code'] },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['primary', 'secondary'] },
      { name: 'RadioGroup', required: true, position: { x: 0, y: 3 } },
      { name: 'Alert', required: false, position: { x: 0, y: 4 } },
    ],
    dependencies: [
      { from: 'QRCode', to: 'Authenticator', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'dashboard-analytics',
    name: '数据分析仪表板',
    description: '综合数据分析界面，展示关键指标、图表和趋势分析',
    category: 'dashboard',
    keywords: ['dashboard', 'analytics', 'metrics', 'kpi', 'charts', 'statistics'],
    complexity: 'high',
    popularity: 92,
    tags: ['analytics', 'visualization', 'business'],
    components: [
      { name: 'Card', required: true, position: { x: 0, y: 0 }, variants: ['metric'] },
      { name: 'Chart', required: true, position: { x: 1, y: 0 }, variants: ['line', 'bar', 'pie'] },
      { name: 'Table', required: false, position: { x: 0, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 2, y: 0 } },
      { name: 'Dropdown', required: false, position: { x: 2, y: 1 } },
      { name: 'Button', required: false, position: { x: 2, y: 2 }, variants: ['secondary'] },
    ],
    dependencies: [
      { from: 'Chart', to: 'DataSource', type: 'required', weight: 1 },
      { from: 'Card', to: 'DataSource', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'dashboard-admin',
    name: '管理员控制台',
    description: '系统管理员后台控制面板，包含用户管理、系统监控和配置',
    category: 'dashboard',
    keywords: ['admin', 'dashboard', 'control', 'management', 'console', 'admin-panel'],
    complexity: 'high',
    popularity: 78,
    tags: ['administration', 'management', 'system'],
    components: [
      { name: 'Sidebar', required: true, position: { x: 0, y: 0 } },
      { name: 'Header', required: true, position: { x: 1, y: 0 } },
      { name: 'Table', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 1, y: 2 }, variants: ['primary', 'danger'] },
      { name: 'Modal', required: false, position: { x: 1, y: 3 } },
      { name: 'Pagination', required: true, position: { x: 1, y: 4 } },
    ],
    dependencies: [
      { from: 'Header', to: 'UserMenu', type: 'required', weight: 1 },
      { from: 'Table', to: 'DataSource', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'ecommerce-product-list',
    name: '商品列表页',
    description: '电商平台商品展示页面，支持筛选、排序和分页',
    category: 'ecommerce',
    keywords: ['ecommerce', 'product', 'catalog', 'shopping', 'list', 'grid'],
    complexity: 'medium',
    popularity: 89,
    tags: ['shopping', 'products', 'e-commerce'],
    components: [
      { name: 'Card', required: true, position: { x: 0, y: 0 }, variants: ['product'] },
      { name: 'Badge', required: false, position: { x: 0, y: 1 } },
      { name: 'Price', required: true, position: { x: 0, y: 2 } },
      { name: 'Rating', required: true, position: { x: 0, y: 3 } },
      { name: 'Filter', required: true, position: { x: 1, y: 0 } },
      { name: 'Sort', required: true, position: { x: 1, y: 1 } },
      { name: 'Pagination', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Card', to: 'Product', type: 'required', weight: 1 },
      { from: 'Filter', to: 'Product', type: 'peer', weight: 1 },
    ],
  },
  {
    id: 'ecommerce-product-detail',
    name: '商品详情页',
    description: '单个商品的详细信息展示，包含图片、描述、规格选择和购买选项',
    category: 'ecommerce',
    keywords: ['product', 'detail', 'ecommerce', 'gallery', 'specs', 'purchase'],
    complexity: 'medium',
    popularity: 91,
    tags: ['product', 'detail', 'e-commerce'],
    components: [
      { name: 'ImageGallery', required: true, position: { x: 0, y: 0 } },
      { name: 'Title', required: true, position: { x: 1, y: 0 } },
      { name: 'Price', required: true, position: { x: 1, y: 1 } },
      { name: 'Rating', required: true, position: { x: 1, y: 2 } },
      { name: 'Description', required: true, position: { x: 1, y: 3 } },
      { name: 'Select', required: true, position: { x: 1, y: 4 } },
      { name: 'Button', required: true, position: { x: 1, y: 5 }, variants: ['primary'] },
      { name: 'Tabs', required: false, position: { x: 2, y: 0 } },
    ],
    dependencies: [
      { from: 'ImageGallery', to: 'Product', type: 'required', weight: 1 },
      { from: 'Select', to: 'Inventory', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'ecommerce-shopping-cart',
    name: '购物车',
    description: '购物车管理界面，支持商品修改、数量调整和结算',
    category: 'ecommerce',
    keywords: ['cart', 'shopping', 'checkout', 'ecommerce', 'basket', 'order'],
    complexity: 'medium',
    popularity: 87,
    tags: ['cart', 'shopping', 'e-commerce'],
    components: [
      { name: 'Table', required: true, position: { x: 0, y: 0 } },
      { name: 'Input', required: true, position: { x: 0, y: 1 }, variants: ['number'] },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['danger'] },
      { name: 'Card', required: true, position: { x: 1, y: 0 }, variants: ['summary'] },
      { name: 'Progress', required: false, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 1, y: 2 }, variants: ['primary', 'large'] },
    ],
    dependencies: [
      { from: 'Table', to: 'Cart', type: 'required', weight: 1 },
      { from: 'Card', to: 'Pricing', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'ecommerce-checkout',
    name: '结算页面',
    description: '电商结算流程，包含地址选择、支付方式和订单确认',
    category: 'ecommerce',
    keywords: ['checkout', 'payment', 'order', 'address', 'billing', 'shipping'],
    complexity: 'high',
    popularity: 82,
    tags: ['checkout', 'payment', 'e-commerce'],
    components: [
      { name: 'Form', required: true, position: { x: 0, y: 0 } },
      { name: 'Input', required: true, position: { x: 0, y: 1 }, variants: ['address'] },
      { name: 'Select', required: true, position: { x: 0, y: 2 } },
      { name: 'RadioGroup', required: true, position: { x: 0, y: 3 } },
      { name: 'Card', required: true, position: { x: 1, y: 0 }, variants: ['summary'] },
      { name: 'Button', required: true, position: { x: 1, y: 1 }, variants: ['primary'] },
      { name: 'SecureBadge', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'RadioGroup', to: 'Payment', type: 'required', weight: 1 },
      { from: 'Form', to: 'Validation', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'cms-article-editor',
    name: '文章编辑器',
    description: '富文本编辑器，支持Markdown、实时预览和媒体上传',
    category: 'content-management',
    keywords: ['editor', 'cms', 'article', 'rich-text', 'markdown', 'content'],
    complexity: 'high',
    popularity: 76,
    tags: ['content', 'editor', 'cms'],
    components: [
      { name: 'Editor', required: true, position: { x: 0, y: 0 }, variants: ['rich-text'] },
      { name: 'Toolbar', required: true, position: { x: 0, y: 1 } },
      { name: 'Preview', required: false, position: { x: 1, y: 0 } },
      { name: 'Upload', required: true, position: { x: 0, y: 2 } },
      { name: 'TagInput', required: false, position: { x: 0, y: 3 } },
      { name: 'Select', required: true, position: { x: 0, y: 4 } },
      { name: 'Button', required: true, position: { x: 0, y: 5 }, variants: ['primary', 'secondary'] },
    ],
    dependencies: [
      { from: 'Editor', to: 'Toolbar', type: 'required', weight: 1 },
      { from: 'Upload', to: 'Media', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'cms-media-library',
    name: '媒体库管理',
    description: '文件管理系统，支持图片、视频和其他媒体文件的上传、组织和预览',
    category: 'content-management',
    keywords: ['media', 'library', 'upload', 'files', 'gallery', 'assets'],
    complexity: 'medium',
    popularity: 73,
    tags: ['media', 'files', 'assets'],
    components: [
      { name: 'Grid', required: true, position: { x: 0, y: 0 } },
      { name: 'Card', required: true, position: { x: 0, y: 1 }, variants: ['media'] },
      { name: 'Upload', required: true, position: { x: 1, y: 0 } },
      { name: 'Filter', required: true, position: { x: 1, y: 1 } },
      { name: 'Search', required: true, position: { x: 1, y: 2 } },
      { name: 'Button', required: true, position: { x: 1, y: 3 }, variants: ['danger'] },
      { name: 'Pagination', required: true, position: { x: 1, y: 4 } },
    ],
    dependencies: [
      { from: 'Grid', to: 'Media', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'social-feed',
    name: '社交动态流',
    description: '社交媒体动态展示界面，支持点赞、评论、分享和无限滚动',
    category: 'social',
    keywords: ['social', 'feed', 'timeline', 'posts', 'activity', 'stream'],
    complexity: 'high',
    popularity: 85,
    tags: ['social', 'feed', 'posts'],
    components: [
      { name: 'PostCard', required: true, position: { x: 0, y: 0 } },
      { name: 'Avatar', required: true, position: { x: 0, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['icon'] },
      { name: 'Textarea', required: true, position: { x: 0, y: 3 } },
      { name: 'ImageGallery', required: false, position: { x: 0, y: 4 } },
      { name: 'InfiniteScroll', required: true, position: { x: 0, y: 5 } },
      { name: 'Dropdown', required: false, position: { x: 1, y: 0 } },
    ],
    dependencies: [
      { from: 'PostCard', to: 'User', type: 'required', weight: 1 },
      { from: 'Button', to: 'Interaction', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'social-messaging',
    name: '即时消息',
    description: '实时聊天界面，支持文字、表情、文件传输和群组聊天',
    category: 'communication',
    keywords: ['chat', 'message', 'messaging', 'conversation', 'real-time', 'communication'],
    complexity: 'high',
    popularity: 79,
    tags: ['chat', 'messaging', 'real-time'],
    components: [
      { name: 'ChatList', required: true, position: { x: 0, y: 0 } },
      { name: 'MessageBubble', required: true, position: { x: 1, y: 0 } },
      { name: 'Input', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 1, y: 2 }, variants: ['icon', 'primary'] },
      { name: 'EmojiPicker', required: false, position: { x: 1, y: 3 } },
      { name: 'Upload', required: false, position: { x: 1, y: 4 } },
      { name: 'Status', required: true, position: { x: 0, y: 1 } },
    ],
    dependencies: [
      { from: 'MessageBubble', to: 'Message', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'analytics-reports',
    name: '数据分析报告',
    description: '生成和查看数据分析报告，支持多种图表和数据导出',
    category: 'analytics',
    keywords: ['report', 'analytics', 'data', 'export', 'charts', 'insights'],
    complexity: 'high',
    popularity: 68,
    tags: ['analytics', 'reports', 'data'],
    components: [
      { name: 'DatePicker', required: true, position: { x: 0, y: 0 } },
      { name: 'Select', required: true, position: { x: 0, y: 1 } },
      { name: 'Chart', required: true, position: { x: 1, y: 0 }, variants: ['multiple'] },
      { name: 'Table', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['primary'] },
      { name: 'Download', required: true, position: { x: 0, y: 3 } },
      { name: 'Share', required: false, position: { x: 0, y: 4 } },
    ],
    dependencies: [
      { from: 'Chart', to: 'DataSource', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'productivity-task-board',
    name: '任务看板',
    description: '看板式任务管理界面，支持拖拽、状态更新和团队协作',
    category: 'productivity',
    keywords: ['task', 'kanban', 'project', 'board', 'management', 'workflow'],
    complexity: 'medium',
    popularity: 81,
    tags: ['task', 'kanban', 'project'],
    components: [
      { name: 'Board', required: true, position: { x: 0, y: 0 } },
      { name: 'Column', required: true, position: { x: 0, y: 1 } },
      { name: 'Card', required: true, position: { x: 0, y: 2 }, variants: ['task'] },
      { name: 'DragDrop', required: true, position: { x: 0, y: 3 } },
      { name: 'Button', required: true, position: { x: 1, y: 0 }, variants: ['icon', 'primary'] },
      { name: 'AvatarGroup', required: false, position: { x: 1, y: 1 } },
      { name: 'Badge', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Column', to: 'Board', type: 'required', weight: 1 },
      { from: 'Card', to: 'Column', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'productivity-calendar',
    name: '日历日程',
    description: '日历组件，支持事件创建、提醒和日程管理',
    category: 'productivity',
    keywords: ['calendar', 'schedule', 'event', 'appointment', 'agenda', 'reminder'],
    complexity: 'medium',
    popularity: 74,
    tags: ['calendar', 'schedule', 'event'],
    components: [
      { name: 'Calendar', required: true, position: { x: 0, y: 0 } },
      { name: 'EventCard', required: true, position: { x: 0, y: 1 } },
      { name: 'Modal', required: true, position: { x: 1, y: 0 } },
      { name: 'Form', required: true, position: { x: 1, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 1, y: 2 } },
      { name: 'TimePicker', required: true, position: { x: 1, y: 3 } },
      { name: 'Button', required: true, position: { x: 1, y: 4 }, variants: ['primary'] },
    ],
    dependencies: [
      { from: 'Calendar', to: 'Event', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'education-course-player',
    name: '在线课程播放',
    description: '视频课程播放界面，支持章节导航、笔记和进度跟踪',
    category: 'education',
    keywords: ['course', 'player', 'video', 'lesson', 'education', 'learning'],
    complexity: 'high',
    popularity: 77,
    tags: ['education', 'video', 'course'],
    components: [
      { name: 'VideoPlayer', required: true, position: { x: 0, y: 0 } },
      { name: 'Progress', required: true, position: { x: 0, y: 1 } },
      { name: 'Sidebar', required: true, position: { x: 1, y: 0 } },
      { name: 'List', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['icon'] },
      { name: 'Note', required: false, position: { x: 0, y: 3 } },
      { name: 'SpeedControl', required: true, position: { x: 0, y: 4 } },
    ],
    dependencies: [
      { from: 'VideoPlayer', to: 'Course', type: 'required', weight: 1 },
      { from: 'List', to: 'Chapter', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'education-quiz',
    name: '在线测验',
    description: '交互式测验界面，支持多种题型和即时反馈',
    category: 'education',
    keywords: ['quiz', 'test', 'exam', 'questionnaire', 'survey', 'assessment'],
    complexity: 'medium',
    popularity: 72,
    tags: ['quiz', 'assessment', 'education'],
    components: [
      { name: 'QuestionCard', required: true, position: { x: 0, y: 0 } },
      { name: 'RadioGroup', required: true, position: { x: 0, y: 1 } },
      { name: 'Checkbox', required: false, position: { x: 0, y: 2 } },
      { name: 'Input', required: false, position: { x: 0, y: 3 } },
      { name: 'Progress', required: true, position: { x: 0, y: 4 } },
      { name: 'Button', required: true, position: { x: 0, y: 5 }, variants: ['primary'] },
      { name: 'Timer', required: true, position: { x: 1, y: 0 } },
    ],
    dependencies: [
      { from: 'QuestionCard', to: 'Question', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'entertainment-streaming',
    name: '视频流媒体',
    description: '视频流平台界面，支持播放列表、推荐和社交功能',
    category: 'entertainment',
    keywords: ['streaming', 'video', 'player', 'playlist', 'entertainment', 'media'],
    complexity: 'high',
    popularity: 83,
    tags: ['streaming', 'video', 'entertainment'],
    components: [
      { name: 'VideoPlayer', required: true, position: { x: 0, y: 0 } },
      { name: 'Playlist', required: true, position: { x: 1, y: 0 } },
      { name: 'Recommendations', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 1 }, variants: ['icon'] },
      { name: 'Rating', required: false, position: { x: 0, y: 2 } },
      { name: 'Share', required: false, position: { x: 0, y: 3 } },
      { name: 'Chat', required: false, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'VideoPlayer', to: 'Video', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'entertainment-music-player',
    name: '音乐播放器',
    description: '音乐播放应用界面，支持播放控制、歌词显示和音效调节',
    category: 'entertainment',
    keywords: ['music', 'player', 'audio', 'playlist', 'streaming', 'sound'],
    complexity: 'medium',
    popularity: 80,
    tags: ['music', 'player', 'audio'],
    components: [
      { name: 'AudioPlayer', required: true, position: { x: 0, y: 0 } },
      { name: 'Progress', required: true, position: { x: 0, y: 1 } },
      { name: 'Controls', required: true, position: { x: 0, y: 2 } },
      { name: 'Button', required: true, position: { x: 0, y: 3 }, variants: ['icon'] },
      { name: 'Playlist', required: true, position: { x: 1, y: 0 } },
      { name: 'Equalizer', required: false, position: { x: 1, y: 1 } },
      { name: 'Lyrics', required: false, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'AudioPlayer', to: 'Track', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'dashboard-monitoring',
    name: '系统监控面板',
    description: '实时系统性能监控界面，展示CPU、内存、网络等指标',
    category: 'dashboard',
    keywords: ['monitoring', 'dashboard', 'metrics', 'performance', 'system', 'real-time'],
    complexity: 'high',
    popularity: 70,
    tags: ['monitoring', 'system', 'real-time'],
    components: [
      { name: 'Chart', required: true, position: { x: 0, y: 0 }, variants: ['line', 'area'] },
      { name: 'Gauge', required: true, position: { x: 1, y: 0 } },
      { name: 'Alert', required: true, position: { x: 0, y: 1 } },
      { name: 'Card', required: true, position: { x: 1, y: 1 }, variants: ['metric'] },
      { name: 'Table', required: false, position: { x: 0, y: 2 } },
      { name: 'Refresh', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Chart', to: 'Metrics', type: 'required', weight: 1 },
      { from: 'Alert', to: 'Monitoring', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'communication-notification-center',
    name: '通知中心',
    description: '系统通知管理界面，支持分类、标记和批量操作',
    category: 'communication',
    keywords: ['notification', 'alert', 'message', 'center', 'update', 'announcement'],
    complexity: 'low',
    popularity: 75,
    tags: ['notification', 'alert', 'messages'],
    components: [
      { name: 'List', required: true, position: { x: 0, y: 0 } },
      { name: 'NotificationCard', required: true, position: { x: 0, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['icon'] },
      { name: 'Filter', required: true, position: { x: 1, y: 0 } },
      { name: 'Checkbox', required: false, position: { x: 1, y: 1 } },
      { name: 'Badge', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'NotificationCard', to: 'Notification', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'ecommerce-wishlist',
    name: '心愿单',
    description: '用户收藏商品管理，支持分类、分享和加入购物车',
    category: 'ecommerce',
    keywords: ['wishlist', 'favorite', 'save', 'collection', 'wish-list'],
    complexity: 'medium',
    popularity: 66,
    tags: ['wishlist', 'favorites', 'shopping'],
    components: [
      { name: 'Card', required: true, position: { x: 0, y: 0 }, variants: ['product'] },
      { name: 'Button', required: true, position: { x: 0, y: 1 }, variants: ['icon'] },
      { name: 'Grid', required: true, position: { x: 0, y: 2 } },
      { name: 'Share', required: false, position: { x: 1, y: 0 } },
      { name: 'Sort', required: false, position: { x: 1, y: 1 } },
      { name: 'Filter', required: false, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Card', to: 'Product', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'social-user-profile',
    name: '用户个人资料',
    description: '用户资料页面，展示个人信息、动态和社交关系',
    category: 'social',
    keywords: ['profile', 'user', 'social', 'bio', 'avatar', 'timeline'],
    complexity: 'medium',
    popularity: 71,
    tags: ['profile', 'user', 'social'],
    components: [
      { name: 'Avatar', required: true, position: { x: 0, y: 0 } },
      { name: 'Header', required: true, position: { x: 0, y: 1 } },
      { name: 'Tabs', required: true, position: { x: 0, y: 2 } },
      { name: 'PostCard', required: true, position: { x: 0, y: 3 } },
      { name: 'Button', required: true, position: { x: 1, y: 0 }, variants: ['primary', 'secondary'] },
      { name: 'Stats', required: true, position: { x: 1, y: 1 } },
    ],
    dependencies: [
      { from: 'Avatar', to: 'User', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'auth-password-reset',
    name: '密码重置',
    description: '密码找回流程，包含邮箱验证和新密码设置',
    category: 'authentication',
    keywords: ['password', 'reset', 'forgot', 'recovery', 'change-password'],
    complexity: 'low',
    popularity: 84,
    tags: ['password', 'reset', 'authentication'],
    components: [
      { name: 'Input', required: true, position: { x: 0, y: 0 }, variants: ['email'] },
      { name: 'Button', required: true, position: { x: 0, y: 1 }, variants: ['primary'] },
      { name: 'Alert', required: true, position: { x: 0, y: 2 } },
      { name: 'Link', required: true, position: { x: 0, y: 3 } },
    ],
    dependencies: [],
  },
  {
    id: 'cms-blog-post',
    name: '博客文章页',
    description: '博客文章展示页面，包含正文、评论和相关推荐',
    category: 'content-management',
    keywords: ['blog', 'post', 'article', 'content', 'reading', 'comments'],
    complexity: 'medium',
    popularity: 69,
    tags: ['blog', 'content', 'reading'],
    components: [
      { name: 'Article', required: true, position: { x: 0, y: 0 } },
      { name: 'Title', required: true, position: { x: 0, y: 1 } },
      { name: 'Author', required: true, position: { x: 0, y: 2 } },
      { name: 'Tag', required: true, position: { x: 0, y: 3 } },
      { name: 'CommentSection', required: true, position: { x: 0, y: 4 } },
      { name: 'Share', required: true, position: { x: 1, y: 0 } },
      { name: 'Related', required: true, position: { x: 1, y: 1 } },
    ],
    dependencies: [
      { from: 'Article', to: 'Content', type: 'required', weight: 1 },
      { from: 'CommentSection', to: 'Article', type: 'peer', weight: 1 },
    ],
  },
  {
    id: 'dashboard-sales',
    name: '销售数据面板',
    description: '销售业绩分析界面，展示销售额、转化率和趋势图表',
    category: 'dashboard',
    keywords: ['sales', 'revenue', 'dashboard', 'analytics', 'performance', 'conversion'],
    complexity: 'high',
    popularity: 78,
    tags: ['sales', 'dashboard', 'analytics'],
    components: [
      { name: 'Card', required: true, position: { x: 0, y: 0 }, variants: ['metric'] },
      { name: 'Chart', required: true, position: { x: 1, y: 0 }, variants: ['line', 'bar'] },
      { name: 'Table', required: true, position: { x: 0, y: 1 } },
      { name: 'Filter', required: true, position: { x: 1, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 1, y: 2 } },
      { name: 'Button', required: false, position: { x: 0, y: 2 }, variants: ['primary'] },
    ],
    dependencies: [
      { from: 'Chart', to: 'Sales', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'productivity-invoice',
    name: '发票管理',
    description: '发票创建和管理系统，支持PDF生成和发送',
    category: 'productivity',
    keywords: ['invoice', 'billing', 'payment', 'receipt', 'accounting', 'business'],
    complexity: 'high',
    popularity: 63,
    tags: ['invoice', 'billing', 'business'],
    components: [
      { name: 'Form', required: true, position: { x: 0, y: 0 } },
      { name: 'Table', required: true, position: { x: 0, y: 1 } },
      { name: 'Input', required: true, position: { x: 0, y: 2 } },
      { name: 'Select', required: true, position: { x: 0, y: 3 } },
      { name: 'Button', required: true, position: { x: 0, y: 4 }, variants: ['primary'] },
      { name: 'Download', required: true, position: { x: 1, y: 0 } },
      { name: 'Preview', required: true, position: { x: 1, y: 1 } },
    ],
    dependencies: [
      { from: 'Form', to: 'Validation', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'analytics-funnel',
    name: '转化漏斗分析',
    description: '用户转化路径分析，识别流失节点和优化机会',
    category: 'analytics',
    keywords: ['funnel', 'conversion', 'analytics', 'path', 'optimization', 'journey'],
    complexity: 'high',
    popularity: 67,
    tags: ['funnel', 'conversion', 'analytics'],
    components: [
      { name: 'FunnelChart', required: true, position: { x: 0, y: 0 } },
      { name: 'StepCard', required: true, position: { x: 0, y: 1 } },
      { name: 'Metrics', required: true, position: { x: 1, y: 0 } },
      { name: 'Recommendations', required: true, position: { x: 1, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 0, y: 2 } },
    ],
    dependencies: [
      { from: 'FunnelChart', to: 'Data', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'education-student-dashboard',
    name: '学生学习中心',
    description: '学生学习进度跟踪和课程推荐界面',
    category: 'education',
    keywords: ['student', 'dashboard', 'learning', 'progress', 'course', 'education'],
    complexity: 'medium',
    popularity: 74,
    tags: ['student', 'education', 'learning'],
    components: [
      { name: 'Progress', required: true, position: { x: 0, y: 0 } },
      { name: 'Card', required: true, position: { x: 0, y: 1 }, variants: ['course'] },
      { name: 'Calendar', required: true, position: { x: 1, y: 0 } },
      { name: 'List', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['primary'] },
      { name: 'Badge', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Card', to: 'Course', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'social-group-chat',
    name: '群组聊天',
    description: '群聊界面，支持@提及、文件分享和群组管理',
    category: 'communication',
    keywords: ['group', 'chat', 'messaging', 'team', 'collaboration', 'communication'],
    complexity: 'high',
    popularity: 72,
    tags: ['group', 'chat', 'team'],
    components: [
      { name: 'ChatList', required: true, position: { x: 0, y: 0 } },
      { name: 'MessageArea', required: true, position: { x: 1, y: 0 } },
      { name: 'MessageInput', required: true, position: { x: 1, y: 1 } },
      { name: 'Button', required: true, position: { x: 1, y: 2 }, variants: ['icon'] },
      { name: 'MemberList', required: true, position: { x: 2, y: 0 } },
      { name: 'Upload', required: false, position: { x: 1, y: 3 } },
      { name: 'Mention', required: true, position: { x: 1, y: 4 } },
    ],
    dependencies: [
      { from: 'MessageArea', to: 'Group', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'ecommerce-product-comparison',
    name: '商品对比',
    description: '多商品对比界面，帮助用户做出购买决策',
    category: 'ecommerce',
    keywords: ['compare', 'comparison', 'product', 'vs', 'versus', 'decision'],
    complexity: 'medium',
    popularity: 58,
    tags: ['comparison', 'product', 'decision'],
    components: [
      { name: 'ComparisonTable', required: true, position: { x: 0, y: 0 } },
      { name: 'Card', required: true, position: { x: 0, y: 1 }, variants: ['product'] },
      { name: 'FeatureList', required: true, position: { x: 0, y: 2 } },
      { name: 'Button', required: true, position: { x: 1, y: 0 }, variants: ['primary'] },
      { name: 'Filter', required: false, position: { x: 1, y: 1 } },
      { name: 'Share', required: false, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'ComparisonTable', to: 'Product', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'cms-knowledge-base',
    name: '知识库',
    description: '帮助文档和知识库系统，支持搜索和分类浏览',
    category: 'content-management',
    keywords: ['knowledge', 'base', 'help', 'docs', 'support', 'faq'],
    complexity: 'medium',
    popularity: 65,
    tags: ['knowledge', 'help', 'documentation'],
    components: [
      { name: 'Search', required: true, position: { x: 0, y: 0 } },
      { name: 'Category', required: true, position: { x: 0, y: 1 } },
      { name: 'ArticleCard', required: true, position: { x: 0, y: 2 } },
      { name: 'Article', required: true, position: { x: 0, y: 3 } },
      { name: 'Pagination', required: true, position: { x: 0, y: 4 } },
      { name: 'Feedback', required: true, position: { x: 1, y: 0 } },
    ],
    dependencies: [
      { from: 'ArticleCard', to: 'Article', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'dashboard-financial',
    name: '财务数据面板',
    description: '财务指标监控，展示收入、支出、利润和预算对比',
    category: 'dashboard',
    keywords: ['financial', 'budget', 'expense', 'revenue', 'profit', 'accounting'],
    complexity: 'high',
    popularity: 71,
    tags: ['financial', 'budget', 'accounting'],
    components: [
      { name: 'Card', required: true, position: { x: 0, y: 0 }, variants: ['metric'] },
      { name: 'Chart', required: true, position: { x: 1, y: 0 }, variants: ['pie', 'bar'] },
      { name: 'Table', required: true, position: { x: 0, y: 1 } },
      { name: 'Filter', required: true, position: { x: 1, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 1, y: 2 } },
      { name: 'Export', required: true, position: { x: 0, y: 2 } },
    ],
    dependencies: [
      { from: 'Chart', to: 'Financial', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'productivity-time-tracking',
    name: '时间跟踪',
    description: '项目时间记录和报告系统，支持计时和统计分析',
    category: 'productivity',
    keywords: ['time', 'tracking', 'timer', 'work', 'project', 'report'],
    complexity: 'medium',
    popularity: 62,
    tags: ['time', 'tracking', 'project'],
    components: [
      { name: 'Timer', required: true, position: { x: 0, y: 0 } },
      { name: 'Button', required: true, position: { x: 0, y: 1 }, variants: ['primary'] },
      { name: 'Table', required: true, position: { x: 0, y: 2 } },
      { name: 'Chart', required: true, position: { x: 1, y: 0 } },
      { name: 'Select', required: true, position: { x: 1, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Timer', to: 'TimeEntry', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'analytics-heatmap',
    name: '数据热力图',
    description: '用户行为热力图分析，展示点击、滚动和交互热点',
    category: 'analytics',
    keywords: ['heatmap', 'behavior', 'analytics', 'click', 'scroll', 'interaction'],
    complexity: 'high',
    popularity: 55,
    tags: ['heatmap', 'analytics', 'behavior'],
    components: [
      { name: 'Heatmap', required: true, position: { x: 0, y: 0 } },
      { name: 'Controls', required: true, position: { x: 1, y: 0 } },
      { name: 'Metric', required: true, position: { x: 1, y: 1 } },
      { name: 'DatePicker', required: true, position: { x: 0, y: 1 } },
      { name: 'Export', required: true, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'Heatmap', to: 'BehaviorData', type: 'required', weight: 1 },
    ],
  },
  {
    id: 'auth-oauth-login',
    name: '第三方登录',
    description: 'OAuth社交登录集成，支持Google、GitHub、微信等',
    category: 'authentication',
    keywords: ['oauth', 'login', 'social', 'google', 'github', 'wechat'],
    complexity: 'medium',
    popularity: 86,
    tags: ['oauth', 'social', 'login'],
    components: [
      { name: 'Button', required: true, position: { x: 0, y: 0 }, variants: ['oauth'] },
      { name: 'Divider', required: true, position: { x: 0, y: 1 } },
      { name: 'Icon', required: true, position: { x: 0, y: 2 } },
      { name: 'Alert', required: false, position: { x: 0, y: 3 } },
    ],
    dependencies: [],
  },
  {
    id: 'communication-video-call',
    name: '视频通话',
    description: '实时视频通话界面，支持屏幕共享和录制',
    category: 'communication',
    keywords: ['video', 'call', 'meeting', 'webcam', 'screen-share', 'conference'],
    complexity: 'high',
    popularity: 69,
    tags: ['video', 'call', 'meeting'],
    components: [
      { name: 'VideoGrid', required: true, position: { x: 0, y: 0 } },
      { name: 'Controls', required: true, position: { x: 0, y: 1 } },
      { name: 'Button', required: true, position: { x: 0, y: 2 }, variants: ['icon', 'danger'] },
      { name: 'Chat', required: false, position: { x: 1, y: 0 } },
      { name: 'ScreenShare', required: false, position: { x: 1, y: 1 } },
      { name: 'Recording', required: false, position: { x: 1, y: 2 } },
    ],
    dependencies: [
      { from: 'VideoGrid', to: 'Media', type: 'required', weight: 1 },
    ],
  },
];

export default SCENARIO_TEMPLATES;
