#!/bin/bash

# Demo-Site 文件查看脚本
# 用于方便查看从 Git 历史恢复的 demo-site 文件

echo "🎨 Demo-Site 文件查看工具"
echo "================================"
echo ""
echo "📋 可用的 demo-site 文件："
echo ""

# 定义 commit hash
COMMIT_HASH="8705169"

echo "📁 核心文件："
echo "  1. App.tsx - 主应用组件"
echo "  2. LandingPage.tsx - 首页"
echo "  3. ComponentLibrary.tsx - 组件库页面"
echo "  4. main.tsx - 入口文件"
echo "  5. styles.css - 样式文件"
echo ""

echo "🧩 组件演示 (按类别)："
echo ""
echo "📝 表单组件："
echo "  - ButtonDemo.tsx - 按钮演示"
echo "  - InputDemo.tsx - 输入框演示"
echo "  - CheckboxDemo.tsx - 复选框演示"
echo "  - SelectDemo.tsx - 选择器演示"
echo "  - SwitchDemo.tsx - 开关演示"
echo ""

echo "💬 反馈组件："
echo "  - AlertDemo.tsx - 警告提示演示"
echo "  - NotificationDemo.tsx - 通知演示"
echo "  - LoadingDemo.tsx - 加载演示"
echo "  - ModalDemo.tsx - 模态框演示"
echo "  - ProgressDemo.tsx - 进度条演示"
echo "  - TooltipDemo.tsx - 工具提示演示"
echo ""

echo "📊 数据展示："
echo "  - CardDemo.tsx - 卡片演示"
echo "  - BadgeDemo.tsx - 标签演示"
echo "  - DataTableDemo.tsx - 数据表格演示"
echo "  - AvatarDemo.tsx - 头像演示"
echo ""

echo "🧭 导航组件："
echo "  - BreadcrumbDemo.tsx - 面包屑演示"
echo "  - HeaderDemo.tsx - 头部演示"
echo "  - SidebarDemo.tsx - 侧边栏演示"
echo "  - TabsDemo.tsx - 标签页演示"
echo "  - PaginationDemo.tsx - 分页演示"
echo ""

echo "📐 布局组件："
echo "  - CardDemo.tsx - 卡片演示 (基础版)"
echo "  - AdvancedCardDemo.tsx - 高级卡片演示"
echo "  - DividerDemo.tsx - 分割线演示"
echo "  - ResponsiveLayoutDemo.tsx - 响应式布局演示"
echo ""

echo "🚀 高级组件："
echo "  - ThemeDemo.tsx - 主题演示"
echo "  - ThemeToggleDemo.tsx - 主题切换演示"
echo "  - AnimatedCardDemo.tsx - 动画卡片演示"
echo "  - MicroInteractionsDemo.tsx - 微交互演示"
echo "  - RadixUIDemo.tsx - Radix UI 集成演示"
echo "  - InteractionStatesDemo.tsx - 交互状态演示"
echo ""

echo "🎨 配方演示："
echo "  - UnifiedRecipeDemo.tsx - 统一配方演示"
echo "  - CompleteRecipeDemo.tsx - 完整配方演示"
echo "  - CreativeRecipeDemo.tsx - 创意配方演示"
echo "  - DTCGRecipeDemo.tsx - DTCG 配方演示"
echo "  - EnhancedRecipeDemo.tsx - 增强配方演示"
echo "  - InteractiveRecipeDemo.tsx - 交互配方演示"
echo "  - StyleRecipeDemo.tsx - 样式配方演示"
echo "  - WorkingRecipeDemo.tsx - 工作配方演示"
echo ""

echo "================================"
echo "📖 使用方法："
echo ""
echo "查看特定文件："
echo "  git show $COMMIT_HASH:demo-site/[文件路径]"
echo ""
echo "例如："
echo "  git show $COMMIT_HASH:demo-site/App.tsx"
echo "  git show $COMMIT_HASH:demo-site/pages/LandingPage.tsx"
echo "  git show $COMMIT_HASH:demo-site/components/forms/ButtonDemo.tsx"
echo ""
echo "保存到临时文件："
echo "  git show $COMMIT_HASH:demo-site/App.tsx > /tmp/App.tsx"
echo ""
echo "查看目录结构："
echo "  git ls-tree $COMMIT_HASH:demo-site"
echo ""
echo "================================"
echo ""
echo "🌐 当前恢复页面地址："
echo "  http://localhost:3100/demo-restore"
echo ""
echo "💡 提示：该页面展示了从 demo-site 恢复的部分内容"